# Site settings
title: Ashis Kumar's CV 
description: Ashis's CV
favicon: /assets/img/Ashis_WB.png
baseurl: https://ashiskumarpal.github.io/
url: https://ashiskumarpal.github.io/
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Ashis Kumar Pal
  title: Interdisciplinary PhD Researcher
  address: Boston,USA.
  email: <a href="mailto:ashispalrony@gmail.com">ashispalrony@gmail.com</a>
  link: https://ashiskumarpal.github.io/AshisKumar/
  weibo:
  github: Ashisrony14
  linkedin: ashis-pal-ipe
  facebook: Crystal.vip3r
  gavatar: /resumecard/assets/img/Ashis-bgr.png
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: <a href="http://twicegroupbd.com/"><span style="color:DeepSkyBlue"><strong>Twice Polybag and Thread Industry Ltd.</strong></span></a>
      location: Dhaka, Bangladesh.
      title: Manager, Production.
      started: 2019
      duration: (July 2019-Sep 2020)
      description: <span style="color:DeepSkyBlue"><strong>Concentration:~ </strong></span> Production of industrial sewing thread, capacity analysis, maintenance, inventory management, lean manufacturing, dyes chemical sourcing.
    - work2:
      company: <a href="https://partexstargroup.com/"><span style="color:DeepSkyBlue"><strong>Partex Star Group</strong></span></a>
      location: Dhaka, Bangladesh.
      title: Master Production Scheduler
      started: 2018
      duration: (Dec 2018 - June 2019)
      description: <span style="color:DeepSkyBlue"><strong>Concentration:~ </strong></span> Demand forecasting,production scheduling,inventory management,supply and operations planning execution.
    - work3:
      company: <a href="https://fakirapparels.com/"><span style="color:DeepSkyBlue"><strong>Fakir Apparels Ltd.</strong></span></a>
      location: Dhaka, Bangladesh.
      title: Executive,Production Planning and Coordination. 
      started: 2017
      duration: (Mar 2017-Sep 2018)
      description: <span style="color:DeepSkyBlue"><strong>Concentration:~ </strong></span> Production planning,capacity analysis,lean Manufacturing,co-ordination and plan execution, waste reduction.
    - work4:
      company: <a href="https://www.bbscables.com.bd/"><span style="color:DeepSkyBlue"><strong>BBS Cables Ltd.</strong></span></a>
      location: Dhaka, Bangladesh
      title: Internship.
      started: 2016
      duration: (Feb 2016-Mar 2016)
      description: <span style="color:DeepSkyBlue"><strong>Concentration:~ </strong></span> Layout design,time and motion study,cable production,quality control of cable manufacturing.
  
  
  educationHistory:
    - education1:
      organization: <a href="https://www.northeastern.edu/"><span style="color:LightSeaGreen"><strong>Northeastern University</strong></span></a>
      location: Boston,MA,USA.
      degree: PhD
      major: Interdisciplinary Engineering ( Cumulative GPA – 3.89/4.00)
      started: Sep 2020
      duration: (Sep 2020 - Running)
      description: <span style="color:LightSeaGreen"><strong>Courses:~ </strong></span> Supervised Machine Learning, Dynamical Processes in Complex Networks, Time Series and Geo-Spatial Data Sciences, Climate Science,Engineering Adaptation, and Policy, Critical Infrastructure Resilience, Complex Networks, Hydrologic and Hydraulic Design, Remote Sensing of the Environment.
      
    - education2:
      organization: <a href="https://www.buet.ac.bd/web/"><span style="color:LightSeaGreen"><strong>Bangladesh University of Engineering and Technology (BUET)</strong></span></a>
      location: Dhaka, Bangladesh.
      degree: B.Sc.
      major: Industrial and Production Engineering ( Cumulative GPA – 3.32/4.00)
      started: Sep 2012
      duration: (May 2012-Feb 2017)
      description: <span style="color:LightSeaGreen"><strong>Courses:~ </strong></span> Operations Research,Probability and Statistics, Manufacturing Process-I and II,Supply Chain Management,Operations Management,Product Design,Computer Integrated Manufacturing.
 
 
  projects:
    - project1:
      name: <span style="color:Indigo"><strong>Network Infrastructure under Compound Extremes.[NICE].</strong></span>
      duration: (May 2021 - Present)
      description: Funded by US Department of Defense(DoD).This hypothesis-guided research will lead to novel frameworks and models for improving the science of resilience with an ultimate, long-term view of providing actionable insights for ensuring DoD’s readiness to unknown and possibly unknowable compounding risks.
    - project2:
      name: <span style="color:Indigo"><strong>Compound flooding impact on lifeline infrastructure network.</strong></span>
      duration: (Fall 2021 - Present)
      description: Understanding of resilience(robustness and recovery) of lifeline infrastructures specifically mass transit railway network in greater Boston area examined under compound flooding (coastal flooding and sea level rise).
    - project3: 
      name: <span style="color:Indigo"><strong>Characterization and delineation of multi model ensembles and multiple initial model ensemble based on complex network analysis.</strong></span>
      duration: (Fall 2021 - Present)
      description: Distinguishing between multiple model ensembles and multiple initial model ensemble and their dynamics using complex network.Exploring geo-clusters,spatial patterns predictive insights,climate dynamics using CMIP6 output data.
    - project4: 
      name: <span style="color:Indigo"><strong>Improving resilience of lifeline infrastructures with network topology and dynamics.</strong></span>
      duration: (Fall 2021 - Present)
      description: Analysing infrastructure network(eight urban metro network worldwide) topology and dynamics(flows of physical quantities in the network) to assess robustness.
    
 
  courses:
    - course1:
      name: <span style="color:SeaGreen"><strong>Supervised Learning with scikit-learn</strong></span>
      by: <span style="color:SeaGreen">DATACAMP</span>
      duration: (March 2020-May 2020)
      facilitator: <span style="color:SeaGreen">Instructor: </span>Hugo Bowne Anderson
    - course2:
      name: <span style="color:SeaGreen"><strong>Lean Production</strong></span>
      by: <span style="color:SeaGreen">edX ~ TUMX</span>
      duration: (Sep 2018-Nov 2018)
      facilitator: <span style="color:SeaGreen">Instructor: </span>Professor Holly ott
 
  languages:
    - language1:
      name: Bengali
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Hindi
      proficiency: Limit
      
  programmingSkills:
    - skill1:
      name: Python
      percentage: 90%
    - skill2:
      name: MATLAB
      percentage: 80%
    - skill3:
      name: ArcGIS
      percentage: 90%
    - skill4:
      name: Tableau
      percentage: 80%
    - skill5:
      name: AutoCAD
      percentage: 80%    
