# Site settings
title: Ashis Kumar's CV 
description: Ashis's CV
favicon: /assets/img/Ashis.JPG
baseurl: https://ashiskumarpal.github.io/
url: https://ashiskumarpal.github.io/
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Ashis Kumar Pal
  title: Interdisciplinary PhD Researcher
  address: Boston,USA.
  email: ashispalrony@gmail.com
  link: https://ashiskumarpal.github.io/AshisKumar/
  weibo:
  github: Ashisrony14
  linkedin: ashis-pal-ipe
  facebook: Crystal.vip3r
  gavatar: /resumecard/assets/img/Ashis-bgr.png
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: <a href="http://twicegroupbd.com/">Twice Polybag and Thread Industry Ltd.</a>
      location: Dhaka, Bangladesh.
      title: Manager, Production.
      started: 2019
      duration: (July 2019-Sep 2020)
      description: <span style="color:blue">Concentration:~</span> Production of industrial sewing thread, capacity analysis, maintenance, inventory management, lean manufacturing, dyes chemical sourcing.
    - work2:
      company: <a href="https://partexstargroup.com/">Partex Star Group</a>
      location: Dhaka, Bangladesh.
      title: Master Production Scheduler
      started: 2018
      duration: (Dec 2018 - June 2019)
      description: <span style="color:blue">Concentration:~</span> Demand forecasting,production scheduling,inventory management,supply and operations planning execution.
    - work3:
      company: <a href="https://fakirapparels.com/">Fakir Apparels Ltd.</a>
      location: Dhaka, Bangladesh.
      title: Executive,Production Planning and Coordination. 
      started: 2017
      duration: (Mar 2017-Sep 2018)
      description: <span style="color:blue">Concentration:~</span> Production planning,capacity analysis,lean Manufacturing,co-ordination and plan execution, waste reduction.
    - work4:
      company: <a href="https://www.bbscables.com.bd/">BBS Cables Ltd.</a>
      location: Dhaka, Bangladesh
      title: Internship.
      started: 2016
      duration: (Feb 2016-Mar 2016)
      description: <span style="color:blue">Concentration:~</span> Layout design,time and motion study,cable production,quality control of cable manufacturing.
  
  
  educationHistory:
    - education1:
      organization: <a href="https://www.northeastern.edu/">Northeastern University</a>
      location: Boston,MA,USA.
      degree: PhD
      major: Interdisciplinary Engineering ( Cumulative GPA – 3.89/4.00)
      started: Sep 2020
      duration: (Sep 2020 - Running)
      description: <span style="color:Crimson">Courses:~</span> Supervised Machine Learning, Dynamical Processes in Complex Networks, Time Series and Geo-Spatial Data Sciences, Climate Science,Engineering Adaptation, and Policy, Critical Infrastructure Resilience, Complex Networks, Hydrologic and Hydraulic Design, Remote Sensing of the Environment.
      
    - education2:
      organization: <a href="https://www.buet.ac.bd/web/">Bangladesh University of Engineering and Technology (BUET)</a>
      location: Dhaka, Bangladesh.
      degree: B.Sc.
      major: Industrial and Production Engineering ( Cumulative GPA – 3.32/4.00)
      started: Sep 2012
      duration: (May 2012-Feb 2017)
      description: <span style="color:Crimson">Courses:~</span> Operations Research,Probability and Statistics, Manufacturing Process-I and II,Supply Chain Management,Operations Management,Product Design,Computer Integrated Manufacturing.
 
  projects:
    - project1:
      name: Test Project.
 
 
  languages:
    - language1:
      name: Bengali
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Hindi
      proficiency: Limit
      
  programmingSkills:
    - skill1:
      name: Python
      percentage: 90%
    - skill2:
      name: MATLAB
      percentage: 80%
    - skill3:
      name: ArcGIS
      percentage: 90%
    - skill4:
      name: Tableau
      percentage: 80%
    - skill5:
      name: AutoCAD
      percentage: 80%    
